### ISSUE TITLE
Error while running 1.3.3 version

### ISSUE THREAD

**Issue by Oieswarya** [ndierckx/Sim-it#11]
I am trying to simulate HiFi reads for Ecoli but I am getting this error.

Start SV Simulation...     cat: /home/Sim-it-master/Output/Long_reads_Ecoli_HAP1.fasta: No such file or directory
cat: /home/Sim-it-master/Output/Long_reads_Ecoli_HAP2.fasta: No such file or directory

I could simulate it for 1.3.2 version.

**Comment by ndierckx** [comment]
Hi,

Yes sorry, I just saw there was a little bug in that version, it should be fixed in 1.3.4

**Comment by Oieswarya** [comment]
Thank you. It works now.
