### ISSUE TITLE
N bases

### ISSUE THREAD

**Issue by asmmahmoud** [ndierckx/Sim-it#15]
Hi @ndierckx 

I have found a lot of N bases in the simulated reads, in some reads the ratio of "N" is greater than or equal to 90% of the read length.  Could you explain to me why the tool generates these N bases ? Is this means this region contains repetitive elements and these bases are hard masked ?

Thank you, 
Asmaa,

**Comment by ndierckx** [comment]
Hi,
Sorry for the late reply, could you send me the config file you used?

**Comment by asmmahmoud** [comment]
Hi @ndierckx
Here is the log file. 

[
[log_sim_Ensembl.txt](https://github.com/ndierckx/Sim-it/files/10992278/log_sim_Ensembl.txt)
](url)

**Comment by ndierckx** [comment]
Hi, I am not sure which reference genome you are using, but doesn't it have large N stretches? Or are those reads with Ns very numerous? You have an option "Replace ambiguous nts(N) = " If you put yes there, Ns in the reference will be replaced by random nucleotides

**Comment by asmmahmoud** [comment]
I used the Ensembl reference genome (main chromosomes) which is here: http://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/
For one of the simulation run, I got 124263/2422824 (5%) reads with N bases and ratio of the N bases ranges from 1% to 94% of the read length. 114807 / 124263 (92.4%) reads have ratio of >= 90% of N bases. Are these numbers expected or they indicate something wrong? 

Thank you,

**Comment by ndierckx** [comment]
there are quite a bit of gaps in the reference genome, so could be normal.
You can use the replace option, or you can use the latest T2T reference genome, which has no more gaps. Or just leave the Ns, I don't think they will influence any simulation you are trying to do

**Comment by asmmahmoud** [comment]
@ndierckx Thank you for your help :)
