### ISSUE TITLE
Tools optional or not ?

### ISSUE THREAD

**Issue by kztyes** [ndierckx/Sim-it#3]
Can i just use a few of these tools instead of all of them to generate a CombiSV ?
For example, I don't want pbsv

**Comment by ndierckx** [comment]
For now Sniffles and pbsv are obligated, it also recommended for the best results
But I will add the option to run without pbsv

**Comment by ndierckx** [comment]
Hi,

The latest version of combiSV (it is a different github page than this one) can run without pbsv. Only Sniffles or cuteSV are obligatory.
