### ISSUE TITLE
Heterozygosity and SV for HiFi reads

### ISSUE THREAD

**Issue by Oieswarya** [ndierckx/Sim-it#9]
Hi, I have been trying to simulate the HiFi reads and I thank you for this tool as this is the first of its kind. My question is what should be the value of heterozygosity and SV for the HiFi reads? Should I keep the default values?
For accuracy, I have given 99% as the accuracy of HifI reads is 99.9%.

**Comment by ndierckx** [comment]
Hi, 
It depends for what you want use the simulation..
Heterozygosity only matters when you are also simulating SVs in the genome.
About the accuracy, you don't need to fill in anything. If you keep it blank it will use the accuracy of the error profile (99.6)

I also uploaded a newer version (1.3.3), where you can use decimal values for accuracy (so you can put 99.9 if you want)

**Comment by Oieswarya** [comment]
Thank you for your prompt reply. I will try the newer version. 
Also after simulating, I saw three files of fasta inside my output directory. Should I concatenate all of the files to get the total number of HiFi reads?

**Comment by ndierckx** [comment]
No, you have one file with all the reads, and also for each haplotype a separate read file (just in case anyone would be interested in that)

**Comment by Oieswarya** [comment]
Thank you
